spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/recime_db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
